name: "sonar_cloud_scan_github_actions"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONOR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=bandarupriyanka
            -Dsonar.projectKey=wdio_sonarcloudAnalysis
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check Quality Gate
        run: |
           sleep 60
           full_response=$(curl -s -u ${{ secrets.SONOR_TOKEN }}: \
           "https://sonarcloud.io/api/qualitygates/project_status?projectKey=wdio_sonarcloudAnalysis")
           echo "Full API response: $full_response"
           quality_gate_status=$(echo $full_response | jq -r .projectStatus.status)
           echo "Extracted quality gate status: $quality_gate_status"
           if [ -z "$quality_gate_status" ] || [ "$quality_gate_status" == "null" ]; then
           echo "Error: Failed to get a valid quality gate status"
           exit 1
           elif [ "$quality_gate_status" != "OK" ]; then
           echo "Quality gate failed: $quality_gate_status"
           exit 1
           else
           echo "Quality gate passed: $quality_gate_status"
           fi
        env:
          SONAR_TOKEN: ${{ secrets.SONOR_TOKEN }}
